import { prisma } from "../infrastructure/database/prisma.js";
import { type RequirementExtractJobPayload } from "../infrastructure/queue/queue.service.js";
import { logger } from "../infrastructure/logging/logger.js";
import { requirementExtractor } from "../modules/intelligence/requirements/requirement-extractor.js";
import { auditService } from "../shared/audit/audit.service.js";
import { RequirementStatus, RequirementCategory } from "@prisma/client";
import type { OcrResultData } from "../modules/intelligence/ocr/ocr.types.js";

/**
 * Asynchronous BullMQ Worker for Requirement Extraction.
 * Consumes `REQUIREMENT_EXTRACT` jobs.
 *
 * Enforces:
 * 1. AI is strictly ADVISORY: All created proposals are marked PROPOSED.
 * 2. Idempotency: Duplicate runs do not create duplicate requirement records.
 * 3. Audit trail: Logs REQUIREMENT_PROPOSED events.
 */
export async function processRequirementExtractJob(payload: RequirementExtractJobPayload): Promise<void> {
  const { tenderId, tenderVersionId, documentId, organizationId, userId } = payload;

  logger.info(
    { tenderId, tenderVersionId, documentId, organizationId, attempt: payload.attempt },
    "Starting asynchronous requirement extraction worker"
  );

  try {
    // 1. Fetch Tender and TenderVersion with tenant isolation
    const tender = await prisma.tender.findFirst({
      where: { id: tenderId, organizationId },
      include: {
        versions: {
          where: { id: tenderVersionId },
        },
      },
    });

    if (!tender || tender.versions.length === 0) {
      logger.error({ tenderId, tenderVersionId, organizationId }, "Tender or version not found for extraction job");
      return;
    }

    const version = tender.versions[0]!;

    // 2. Fetch OCR text or tender version content
    let ocrData: OcrResultData = {
      text: "",
      pageCount: 1,
      pages: [],
      extractionMethod: "HYBRID_OCR",
      engine: "bidsure-ocr-engine",
      confidence: 0.95,
    };

    let resolvedDocumentId = documentId;

    if (resolvedDocumentId) {
      const ocrRecord = await prisma.oCRResult.findFirst({
        where: { documentId: resolvedDocumentId, isCurrent: true },
      });
      if (ocrRecord && ocrRecord.text) {
        ocrData = {
          text: ocrRecord.text,
          pageCount: ocrRecord.pageCount,
          pages: (ocrRecord.pages as any) || [{ page: 1, text: ocrRecord.text }],
          extractionMethod: (ocrRecord.extractionMethod as "HYBRID_OCR" | "IMAGE_OCR" | "NATIVE_PDF") || "HYBRID_OCR",
          engine: ocrRecord.engine,
          confidence: ocrRecord.confidence || 0.95,
        };
      }
    } else {
      // Check if there are attached tender documents
      const attachedDoc = await prisma.tenderDocument.findFirst({
        where: {
          tenderId,
          OR: [{ tenderVersionId }, { tenderVersionId: null }],
        },
        include: {
          document: {
            include: {
              ocrResults: {
                where: { isCurrent: true },
                take: 1,
              },
            },
          },
        },
      });

      if (attachedDoc && attachedDoc.document.ocrResults[0]?.text) {
        const ocrRecord = attachedDoc.document.ocrResults[0];
        resolvedDocumentId = attachedDoc.document.id;
        ocrData = {
          text: ocrRecord.text || "",
          pageCount: ocrRecord.pageCount,
          pages: (ocrRecord.pages as any) || [{ page: 1, text: ocrRecord.text || "" }],
          extractionMethod: (ocrRecord.extractionMethod as "HYBRID_OCR" | "IMAGE_OCR" | "NATIVE_PDF") || "HYBRID_OCR",
          engine: ocrRecord.engine,
          confidence: ocrRecord.confidence || 0.95,
        };
      } else {
        // Synthesize OCR text from version title, description, and content snapshot
        const contentStr = version.content ? JSON.stringify(version.content) : "";
        const compositeText = `${version.title}\n\n${version.description || ""}\n\n${contentStr}`;
        ocrData = {
          text: compositeText,
          pageCount: 1,
          pages: [{ page: 1, text: compositeText, confidence: 0.9 }],
          extractionMethod: "HYBRID_OCR" as const,
          engine: "bidsure-ocr-engine",
          confidence: 0.9,
        };
      }
    }

    // 3. Extract structured requirement proposals via prompt-defended extractor
    const extractionResult = await requirementExtractor.extractRequirements(
      tenderVersionId,
      ocrData,
      resolvedDocumentId
    );

    logger.info(
      { tenderVersionId, proposalsCount: extractionResult.proposals.length },
      "Requirement proposals generated by extraction engine"
    );

    // 4. Persist proposals idempotently in PROPOSED state
    let createdCount = 0;
    for (const p of extractionResult.proposals) {
      // Check if requirement with this identifier already exists for this tender version
      const existingReq = await prisma.requirement.findUnique({
        where: {
          tenderVersionId_identifier: {
            tenderVersionId,
            identifier: p.identifier,
          },
        },
      });

      if (existingReq) {
        logger.debug({ identifier: p.identifier, tenderVersionId }, "Proposal with identifier already exists; skipping");
        continue;
      }

      // Create Requirement and initial RequirementVersion (v1, PROPOSED) atomically
      await prisma.$transaction(async (tx) => {
        const req = await tx.requirement.create({
          data: {
            organizationId,
            tenderId,
            tenderVersionId,
            identifier: p.identifier,
            category: p.category,
          },
        });

        const reqVersion = await tx.requirementVersion.create({
          data: {
            requirementId: req.id,
            tenderVersionId,
            versionNumber: 1,
            status: RequirementStatus.PROPOSED,
            category: p.category,
            title: p.title,
            description: p.description,
            mandatory: p.mandatory,
            condition: p.condition ?? null,
            operator: p.operator ?? null,
            threshold: (p.threshold as any) ?? null,
            expectedValue: p.expectedValue ?? null,
            requiredEvidenceType: p.requiredEvidenceType ?? null,
            sourceClause: p.sourceClause,
            sourcePage: p.sourcePage,
            sourceText: p.sourceText,
            sourceDocumentId: resolvedDocumentId ?? null,
            aiGenerated: true,
            aiModel: p.aiModel,
            aiModelVersion: p.aiModelVersion,
            aiConfidence: p.confidence,
            createdBy: userId ?? null,
          },
        });

        await tx.requirement.update({
          where: { id: req.id },
          data: { currentVersionId: reqVersion.id },
        });

        // Audit log
        await auditService.logEvent({
          organizationId,
          userId: userId ?? null,
          action: "REQUIREMENT_PROPOSED",
          entityType: "REQUIREMENT",
          entityId: req.id,
          newState: {
            requirementId: req.id,
            identifier: req.identifier,
            status: RequirementStatus.PROPOSED,
            versionNumber: 1,
            title: p.title,
          },
          metadata: {
            tenderVersionId,
            aiConfidence: p.confidence,
          },
        });
      });

      createdCount++;
    }

    logger.info(
      { tenderVersionId, createdCount, totalProposals: extractionResult.proposals.length },
      "Completed asynchronous requirement extraction job"
    );
  } catch (err: any) {
    logger.error(
      { tenderId, tenderVersionId, err: err.message },
      "Error processing requirement extraction worker job"
    );
    throw err;
  }
}
